### ISSUE TITLE
"maximization context"?

### ISSUE THREAD

**Issue by zachdj** [wildart/Evolutionary.jl#102]
Several of the selection functions (e.g. [Evolutionary.roulette](https://wildart.github.io/Evolutionary.jl/dev/selection/#Evolutionary.roulette) ) have this note:

> Note: Best used in maximization context.

My understanding of `Evolutionary.optimize` is that it always minimizes the objective function.  Is there an actual context where `optimize` will maximize the objective?  Or maybe this note is meant to distinguish cases where we are searching for the largest-negative result as opposed to minimizing to 0?

Either way,  I think it would be helpful to clarify :)

**Comment by wildart** [comment]
The roulette selection allocates proportional to a fitness. Because the package always performs minimization of a fitness function, in order to use it for maximization, one needs to modify fitness function so when it's minimized the largest fitness is selected, e.g. make fitness negative. This trick will work with roulette selection because negative fitness will be properly normalized.

However, when the fitness is positive and minimized to 0, you get an opposite to what roulette selection supposed to do - allocate large roulette sectors for fittest offspring, e.g. Rosenbrock function.

**Comment by zachdj** [comment]
Got it, thanks
