### ISSUE TITLE
Ability to check viability (over a predicate) of Mutation and crossover operations

### ISSUE THREAD

**Issue by Azzaare** [wildart/Evolutionary.jl#75]
This issue follow #74 (now closed as the real problem has been identified).

> Is it possible to provide a predicate for viable individuals at each generation so that mutation and crossover are remade if the individual is not viable?

(btw, is there a place to ask questions and chat about Evolutionary.jl?)

**Comment by Azzaare** [comment]
I wonder if I can work it around by encapsulating my crossover and mutation functions `f`s by other functions that test the viability and call those `f`s again ...

**Comment by Azzaare** [comment]
It more or less works out with hand-made functions, but it might be nice to have a viability predicate that default to `true` when we do a crossover or a mutation.

Now, I actually have a real problem with the following code in `api/types.jl`
```julia
function NonDifferentiable(f, x::BitArray)
    xs = BitArray(zero(eltype(x)) for i = 1:length(x)) # this line generate a non viable individual
    NonDifferentiable{Real,typeof(xs)}(f, f(xs), xs, [0,])
end
```
Is it necessary by the GA  to have `xs` be full of zeros?

**Comment by wildart** [comment]
> Is it possible to provide a predicate for viable individuals at each generation so that mutation and crossover are remade if the individual is not viable?

Viability of the individual is determined by its fitness value. There is no other way, otherwise it would not be an evolutionary algorithm.

> I wonder if I can work it around by encapsulating my crossover and mutation functions fs by other functions that test the viability and call those fs again ...

You can write a wrapper function (closure) that would do that for any crossover/mutation operation

> Is it necessary by the GA to have `xs` be full of zeros?

This is just a wrapper for a fitness function with an additional storage for the intermediate result, which is `xs`.

---

I think that you have a problem with your initial population. Use random bit vectors to initialize your population, see example in `test/onemax.jl`.

**Comment by Azzaare** [comment]
Thank you for your answer! I have solved the problem by giving infinite fitness to "non-viable"  individuals.
