### ISSUE TITLE
Evolutionary.jl fails to solve simple task that analogous simple python script solves without any problem.

### ISSUE THREAD

**Issue by damiankucharski** [wildart/Evolutionary.jl#93]
Hello, I've just started getting into Julia ecosystem and I wanted to compare performance of genetic algorithm solving simple task both in Julia and Python.

I've based the experiment on the code from this article: https://machinelearningmastery.com/simple-genetic-algorithm-from-scratch-in-python/#:~:text=an%20objective%20function.-,Genetic%20Algorithm%20for%20OneMax,-In%20this%20section

I've run the code implementing OneMax basically without modifications, I have only changed the number of bits from default 30 to 100.
The algorithm finds the correct solution in 36 iterations when set numpy.random.seed(0).

Running the following snippet in Julia multiple times results in Status: failure after exceeding 100 iterations and never being able to get value of objective function lower than -90. 
```

n_iter = 100
# bits
n_bits = 20
# define the population size
n_pop = 100
# crossover rate
r_cross = 0.9
# mutation rate
r_mut = 1.0 / float(n_bits)

onemax(x) = -sum(x)

res = Evolutionary.optimize(onemax, BitVector(zeros(100)), GA(populationSize=n_pop, crossoverRate = r_cross, mutationRate = r_mut, selection=tournament(5), mutation=flip, crossover=singlepoint), Evolutionary.Options(iterations=n_iter))
```

Example output:

```
* Status: failure (reached maximum number of iterations)

 * Candidate solution
    Minimizer:  Bool[1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    Minimum:    -85
    Iterations: 100

 * Found with
    Algorithm: GA[P=100,x=0.9,μ=0.05,ɛ=0]

 * Work counters
    Seconds run:   0.005 (vs limit Inf)
    Iterations:    100
    f(x) calls:    10184

```
Do you know why it may be the case?

**Comment by wildart** [comment]
You may want to increase mutation rate. The `flip` mutation performs one mutation per individual:
https://github.com/wildart/Evolutionary.jl/blob/8472ab0bf976ae45a267a67a5465154173bcd53b/src/mutations.jl#L116-L118
The mutation rate specifies whether this **one** bit flip will happen for one individual in the population.

In case of the python code, the probability of mutation is `n_bits` higher, because mutation can occur multiple times for the individual, so it's multiple mutations per individual:
```python
for i in range(len(bitstring)):
    # check for a mutation
    if rand() < r_mut:
        # flip the bit
        bitstring[i] = 1 - bitstring[i]
```
What you see in the julia example is a low performance associated with inability to flip zeros to ones. So, if you increase `mutationRate`  in julia example, you should be able to get better results.

Moreover, the python example always runs for 100 iterations of the optimization, while the julia optimization evaluates the fitness function change and terminates if this change less than some predefined tolerance. Again, less iteration results in less mutation needed for acquiring more ones in genome. Try to set `abstol` parameter to `0` to disable this check and force termination after the specified number of iterations, `iterations` parameter.

**Comment by damiankucharski** [comment]
Hello @wildart
Thanks for your help!
So just to confirm - in the case of Evolutionary.jl the mutation rate is a probability of a single individual to mutate, correct?
So to match the python settings I should set the mutation rate to 100% as in case of python script each cell in chromosome has  1/len(chromosome) chance to mutate, so it is on average 1 flip per individual.

**Comment by wildart** [comment]
I do not think it translates directly in the way you described, it would depend on population size as well. The mutation rate in the python code controls how the each individual is mutated; in `Evolutionary`, the mutation rate specifies how the population is mutated, i.e. if the individual in the population should be mutated or not. The mutation always happens for a selected individual.
It's common to view the crossover as a main mutation operation that drives population evolution, while mutation operator as a secondary which allows to avoid a capture in the local minima. But after all, selection of the parameters is problem dependent.  

Back to your example, if you set high both operator rates, it's counter productive - too much randomness, and solution become unstable. So, usually, the crossover rate is set high, i.e. 0.9 in your case, and the mutation rate is low. `1.0 / float(n_bits)` is not enough as only 1% is about to be mutated, and the mutation operator changes 1% of the individual. You get 0.01% mutations in the population. It's to low, and you can see it from the fitness value 90% of optimal value. If you set 100% of mutation rate, it's also a problem: you wont have a stable set of optimal solutions for evolutionary process, because every individual will be mutated. I tried 10-20% rate of mutation, and got quite stable results - always reaching the optimal solution.

**Comment by damiankucharski** [comment]
Okay, thank you for help :)
